[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
rv-brand = "crimera ReVanced"
arch = "arm64-v8a"
included-patches = "'Hide FAB' 'Customize Navigation Bar items' 'Hide promote button' 'Hide Community Notes' 'Hide Banner'"
